### ISSUE TITLE
Is a 'repository' the correct place for a discussion page?

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/Forum-Wiki#1]
I'm not sure if 'repository' or just an 'issue in an existing repository' is the appropriate place to post discussions?
Any clarification?

**Comment by allisonpenko** [comment]
Meg and I are wondering the same thing. Might be a good place so it's not all mixed in with the code. But maybe it should belong in the webpage repository? @Coastal-Imaging-Research-Network/managers

**Comment by allisonpenko** [comment]
So now we think the answer is yes - but we renamed it "Forum-Wiki". Let's use this repository to house all the discussion and wiki docs for all things Coastal Imaging. The Webpage repository will just be for editing the website. We can link to the Forum and Wiki on the website. What do y'all think?

**Comment by mpalmsten** [comment]
I did some searching and found that GitHub itself just launched a [forum](https://platform.github.community/) to provide direct communication between developers and engineers. The forum uses [discourse](https://www.discourse.org/). Maybe we could put a discourse forum into our CIRN website... Disclaimer - I have no idea how to actually do this, but we can figure it out if it makes sense.

**Comment by SRHarrison** [comment]
That discourse looks good...

**Comment by SRHarrison** [comment]
@allisonpenko, I like the rename... 
Just thinking out loud here about potential organizational hiccups - this will be the place for discussion and wiki docs for Coastal Imaging... Then will there be a similar forum on the code repository for code related chatter (i.e. installation, instructions, debugging, etc.)? Or should all that type of stuff be included here at CIRN forum? 
I suspect that once things are up and running that the lines will be blurred and topics might need to be redirected?

**Comment by SRHarrison** [comment]
I forget what we decided about how to include discussions? 
Was there a problem with discourse? 

I ask because I would like to document q&a discussions, e.g. recent conversations with John Stanley about observatory hardware and settings.

**Comment by mpalmsten** [comment]
Hi Shawn,

We decided to use this section for general discussions, and different repositories to discuss specific code discussions.  If your discussions with John can be easily formatted into wiki pages, I think that might be the best place to put them.
