### ISSUE TITLE
Decide on CIRN License

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Forum-Wiki#10]
Add research and add license information to repositories

**Comment by mpalmsten** [comment]
[Here's](https://github.com/blog/1530-choosing-an-open-source-license)
 a blog post about choosing an open source license. This seems like a good place to start.

I think @thesser1 also has experience with open source licenses

**Comment by jstanleyx** [comment]
GPLv3 seems to do what we want. It is extremely verbose, however.

**Comment by RobHolman** [comment]
was there supposed to be a link with this?

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu

**Comment by RobHolman** [comment]
I have heard from several sources (John and Ian Turner/Doug that the GNU license GPL version 3 is the good choice.  They also say that we should talk to someone who has done this.
