### ISSUE TITLE
Member management

### ISSUE THREAD

**Issue by allisonpenko** [Coastal-Imaging-Research-Network/Forum-Wiki#17]
I updated the permissions on all our repositories. Our default permission is now read access for new members. I also protected the master branches of all the repositories. This now solves the problem of people committing to different branches. All changes must be committed to a non-protected branch and then approved by at least one admin to merge into the master. Additionally, I created 2 more Teams (besides our managers) to delineate the permissions of the CIRN members and give us flexibility of who we allow to edit the code. They are as follows: 

**managers:** us - write permission to everything. Approve pull requests. Manage members. Keep this group small

**developers**: for people interested in developing code and editing the wiki. write/push access to Code repositories (cBathy, UAV, Support Routines) and to the Wiki. All pull requests must be approved by a manager.

**contributors:** for people wanting to add documentation or information to the Wiki. write/push access to the Forum-Wiki repository. Edits DO NOT have to be approved by admins (I figured this would be cumbersome and a lot of work for us, and frankly quite annoying to have all our edits approved by someone else. But let me know if anyone is highly against this. 

**members**: only read access. Can clone, but not push.

**general public**: only read access .Can clone but not push. Note, this is the same access as members. Therefore, we really only invite people to be members if they are going to need/want permissions belonging to the 1st three types.  

Thoughts or comments?

**Comment by RobHolman** [comment]
Excellent work.  Thanks.  Regarding the non-control of the wiki, this is probably a fair experiment.  But I'm a bit concerned in that incorrect material may appear and the default will be that we need to watch for it without knowing when anything is posted.  So it's a  bit of a concern.

**Comment by allisonpenko** [comment]
OK - learning more by the day. An admin has to INVITE a person to be a member. I clarified this on the website, but basically, there is no button for someone to join as a member. They have to personally contact an admin and ask to be added. I don't see this as a huge problem, as most everybody in the community knows at least one of us AND a person ONLY needs to be a member if they are going to be contributing to the code or wiki (see comment above).

BUT we might think about have a generic CIRN gmail that we can advertise to send requests. Of course this is more work, but may be something to think about for the future.

**Comment by allisonpenko** [comment]
@Coastal-Imaging-Research-Network/managers Sorry Jenna - that was my fault. When I set the permissions for specific teams, I forgot to give the manager team admin access to all the repositories! It's fixed now. ALL- PLEASE read the Member management thread for clarification on member access [HERE](https://github.com/Coastal-Imaging-Research-Network/Forum-Wiki/issues/17). We as managers have access to everything. Please do not add anyone to the Manager group without discussing with the other managers first. You can add anyone to the developer or contributor teams anytime.
