### ISSUE TITLE
Aiming cameras at a multi-camera station

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/Forum-Wiki#19]
Does anyone have advice for a methodical way to aim cameras while in the field to establish a multi-camera station? 

I've carefully planned out the station with the tools described in [Installation Design](https://github.com/Coastal-Imaging-Research-Network/Forum-Wiki/wiki/Installation-Design), but when I actually go to establish the view in the field things get pretty loose. 
E.g. the bright sun makes it difficult to see the camera imagery on a laptop, which impacts my ability to establish appropriate focus, digital camera settings, and field-of-view. Rather than a 5% overlap, I ended up with more like 20% overlap. 

Any tips / tricks to make the installation more precise are welcome.
Thanks!

**Comment by mpalmsten** [comment]
Aiming cameras is tricky. I usually export the plots that I made for designing a station to a KML file and plot them in Google Earth. Then, I try to find landmarks (buildings, jetties, etc) to help me line up the pointing angles when I'm in the field. I usually set the cameras so I have a long depth of field and do the focusing before I mount the cameras.

**Comment by jstanleyx** [comment]
Yes, focus before mount is important. Also, focus with the f-stop all the way open, then close down to the final value (f8 is what typically use). That way you have best focus for the desired distance, and the increase in depth of field as you close the lens down works in your favor. 

You really need a display that you can see when you do the actual installation. There isn't a good way around that. Put a blanket over your head and laptop if you need to get into a darker environment. I've tried making it darker by closing my eyes, but apparently my eyelids are too transparent and this system didn't work well.

If you have done a good design which includes azimuth and predicted FOV, then you can try to preset the angles of the cameras before installing them. I just had a station on the Washington coast where three cameras were mounted on the top of a pole. Very hard to point them after they went up the pole. All three were mounted on one mount, so I could use an inclinometer (from the local hardware store) to set the tilt, and a protractor to set the azimuths (actually difference in angles between cameras). Then I fine-tuned the azimuth while all three were on the ground, looking at things in the distance to get the right overlap. (The cameras don't care if they are looking at waves in the water or houses and trees when you set the overlap.) Once they went up the pole, it was "good enough". Remember, you can have perfect or you can cover what you need....

**Comment by SRHarrison** [comment]
Great suggestions. I'll do this next time...
