### ISSUE TITLE
Agenda for phone call

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Forum-Wiki#2]
Coastal Imaging Research Network Meeting
• Forum – this is high priority
o   Discourse.org – it’s what GitHub uses for its forums, probably a good choice
o   How do we put Discourse on GitHub page? 
• How are repositories organized? Does it make sense?
o   Webpage
o   CIL
o   Toolboxes separate?
o   What about other tools we write?
 Processing data from non-Argus sites (My Matlab code for making stacks from multiple cams)
 Stereo stuff
 Python
• Structure of website/wiki/repository
o   Forum on webpage?
o   General wiki in webpage repository? That’s what I started
• Standards for code writing – case, style, tests?
• Other than webpage/wiki/forum, what else needs to be completed before going public?
• Goal: Have it public by AGU so we can advertise
• Any updates from Deltares?
• Working on summary document from workshop – will send something out end of this week/weekend
• For longer term – open source scripting (python) – has pros and cons
• Met with Nicole Gasparini, Tulane – she has taken her advisor’s landscape model open source over last 5 years and has good suggestions/guidance
• Include CIRN  in Community Surface Dynamics Modeling System (CSDMS)?

**Comment by allisonpenko** [comment]
I like this agenda. Good job Meg

**Comment by SRHarrison** [comment]
Nice job making a reply ...

**Comment by mpalmsten** [comment]
Here's a summary for the phone call:
- We will use this issues site as the forum because it is easy well organized and searchable. It is better than hosting a forum on another website. The forum will have active discussion topics. When discussion is solidified we will incorporate the results of the discussion into the wiki. Examples of discussion topics might be UAVs or distortion.
- We will continue to upgrade the website, this includes adding summary information and important links. The website will be the main place we will send people.
- There will be distinct repositories for toolboxes (CBathy, UAV) that work independently of the "traditional" CIL code that requires the database and Argus directory structures.
- We want functions that will can handle both database style processing and non-database style processing.
- We will adopt traditional Argus case/style/naming conventions. These will be described in the wiki.
- Over time, we will likely develop tests that must be run when a pull request occurs. Initially, an expert user will have to check the code.
- We will have ongoing discussions about what will initially be included in the CIRN repositories and what we will leave out.
- Homework: Propose some concrete goals and timelines for wiki and repository.
