### ISSUE TITLE
Broken links !!

### ISSUE THREAD

**Issue by jstanleyx** [Coastal-Imaging-Research-Network/Forum-Wiki#20]
It appears something has changed in Github and now many of the links in the Wiki are broken. I don't think this is a personal settings difference, It think Github did something.

Every link that has spaces in the target are now invalid. I found this on the Hardware Corner page. You can identify these because instead of a simple link there is a full URL listed.

To fix this, replace spaces in the target with %20 -- the URL encoding for a space.

**Comment by allisonpenko** [comment]
All fixed. The links just needed a dash "-" in the space. GitHub automatically adds a dash in all spaces in their links. Best practice is to just copy and paste from the address line when inserting links on the wiki
