### ISSUE TITLE
cBathy demonstration material during the Boot camp

### ISSUE THREAD

**Issue by trkim117** [Coastal-Imaging-Research-Network/Forum-Wiki#23]
Hi Everybody!
I am looking for cBathy demonstration m file and data(mat) file which Meg used during her
demonstration.
I remember it includes several functions for running and debugging inside, such as democBathy.m and etc.
Could you let me know where I can find them?

Thanks!

**Comment by SRHarrison** [comment]
Hi Kim!
Meg added those files into the [development branch of the cBathy repository](https://github.com/Coastal-Imaging-Research-Network/cBathy-Toolbox/tree/development). So, if you git the updated development branch you will see there's a new folder called 'cBathyDemoWithPlots'. 
I think it will soon be pushed into the master branch, but we need to wait for it to be authorized by our supreme branch manager @allisonpenko.

**Comment by allisonpenko** [comment]
I just created a pull request to merge into the master code. @SRHarrison  if you could merge it - it will then be in the master code for you @trkim117

**Comment by trkim117** [comment]
Thank you very much!!
