### ISSUE TITLE
Zoom lens distortion correction-Help!

### ISSUE THREAD

**Issue by trkim117** [Coastal-Imaging-Research-Network/Forum-Wiki#25]
Hi! Everybody!!
Is there anyone who has an experience on **zoom lens distortion correction**?
Intrinsic calibration is usually done inside the lab but sometimes we need to change the
zoom as well as angle on the top of the tower.
In this case, intrinsic calibration data already done in the lab is of no use.
After we fix the zoom on the top and bring  it back down, do we have to do same process
again for lens correction?
I wonder if any one has good idea which makes this problem easier.

The other thing is if it is easy to **add one more option for fx(fy) to the flags of
six extrinsic parameters.**

Thank you for your time!!
KIM

**Comment by hokiespurs** [comment]
Hi @trkim117 ,

You could definitely add a flag to incorporate focal length in the regression, but I would worry that the nonlinear lens distortion parameters (k1,k2,k3,p1,p2) might also change.  Zoom lenses have multiple lenses built in, their relative contributions to the nonlinear distortion might vary as you move them around while zooming in and out.  I haven't looked into this and I could definitely be wrong (maybe someone else who has will chime in), but it might be worth experimenting in the lab with your specific lens.

Also, by adding focal length as a parameter you'll definitely want to add more control to really lock down the exterior orientation.  It won't be as accurate as a fixed focal length, but depending on your accuracy requirements, I'm sure you could make something work.  

Maybe a good method would be to:

1. Calibrate the camera in the lab
2. Put the camera on the tower in its final location and take an image with GCPs in the scene
3. Solve for exterior orientation and store the X,Y,Z value
4. Adjust the zoom and rotations
5. Solve for rotation angles and focal length but hold the previous X,Y,Z value fixed

This would give you some more degrees of freedom in your regression, as you're only solving for focal length and rotations.  Again, this is assuming nonlinear lens distortion parameters are constant.

Honestly, the most straightforward way would be to do as you said: put camera on tower, figure out the zoom you want, lock the zoom down, take the camera back down and do a camera calibration, then put it back.  This might take you an extra day, but it is the most straightforward approach and will likely give you better results.

If you choose to try one of the other approaches, be sure to share how it goes!

**Comment by trkim117** [comment]
Thanks Hokiespurs !!
The procedure you suggested is a good idea and worth to try if the lens distortion parameters are constant as you mentioned. I will let you know what I get after I try.
Also, I am thinking to use some kind of  long stick to do intrinsic calibration on the site.
Thank you again for your time and advice!!
