### ISSUE TITLE
Contribution Guidlines

### ISSUE THREAD

**Issue by SBFRF** [Coastal-Imaging-Research-Network/Forum-Wiki#28]
Hello, 
I've looked around, and maybe I've missed it, but I would suggest a place that lays out guidelines for repository contributions. 

_____________________________
These things might include: 

- git best practices.  Might include: 
  - branching off development 
  - pull requests
  - admin reviews
  -  forking PR #27 

- Code documentation requirements/suggestions:
  - provide guidance to contributor the requirement of code comments    for new toolbox's or ongoing contributions help guides etc. 
  - both heading comments (for help) and inline comments describing complex portions of code
  - API requirements (this might be involved)

- package requirements:  what matlab toolboxes are contributor limited to or make assumptions of use for users?

- language requirements (is this only matlab ??)

- TODO list that might suggest ways people can contribute if they were willing 

- how users can change role in repository (member, developer ... etc)

- Links to external documentation, mailing lists, or a code of conduct.

- Community and behavioral expectations.
_____________________
I'm sure the would be other useful things and like I said, maybe I missed the location on some of this stuff if it's out there.  I'm happy to write some of this (if its not already written) and help contribute to this, but I think the community admins would need to provide input as to how to proceed.

**Comment by emmettk** [comment]
As someone who is new to CIRN, this all sounds great. I especially like the idea of a To Do list so new people like me can start working in a useful direction. At the bootcamp, some minor changes and future feature additions were mentioned as we went through - maybe a list of things like that would be a place to start?

**Comment by SBFRF** [comment]
Hey @emmettk Thanks for chiming in!  Its good to hear that you would find this useful (that means its worth doing 👍).   I think we're having discussions on some of these topics following the boot camp (and meeting).   I think we're going to try to come up with a plan of attack to solve some of these issues.  Stay tuned!

**Comment by KateBrodie** [comment]
@SBFRF @emmettk 

Great suggestions!  Where would be the best place for the To-Do list to live? As Issues on each repository page, for example [here](https://github.com/Coastal-Imaging-Research-Network/cBathy-Toolbox/issues) or [here](https://github.com/Coastal-Imaging-Research-Network/UAV-Processing-Toolbox/issues)? Or is there a better place?

We had also experimented with creating [projects](https://github.com/orgs/Coastal-Imaging-Research-Network/projects), but hadn't used them yet...

**Comment by SBFRF** [comment]
According to this article https://help.github.com/articles/setting-guidelines-for-repository-contributors/ creating a "contributin.[md/txt]" in the root/docs/.github  and github will pick it up and highlight it for users when they're exploring the repository.  The article also has good examples of others contribution guidelines.

**Comment by eswanson-usgs** [comment]
[30aa05f](https://github.com/Coastal-Imaging-Research-Network/cBathy-Toolbox/commit/30aa05f1ee6964461578e8cd7f3c950a9a115f09) closed this issue in cBathy-Toolbox
