### ISSUE TITLE
Portable Argus Towers

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/Forum-Wiki#3]
A colleague is looking to setup an Argus system to observe a coastline along the north slope of Alaska. The region is completely flat, without much elevation or any firm structures to mount a camera system.
Further, the ice sheet covers the region for 7-8 months of the year, so something able to be deployed for the summer months is ideal. 
The trailer systems described by @JennaBrown (and @KateBrodie) and @MickHaller seem like they would work well (See images below). 
Does anyone have specs on building such a platform? I'd like to know about rough cost to build and general work flow. 
Thanks!

![frf_rapiddeploytower](https://cloud.githubusercontent.com/assets/22459629/19134477/1a847ae2-8b13-11e6-8d8d-8f6544254f58.png)   -from Jenna Brown, USGS

![haller_tower](https://cloud.githubusercontent.com/assets/22459629/19134478/1e8b8ad6-8b13-11e6-813f-d2ac59d8fe9f.png)  -from Mick Haller, OSU

**Comment by RobHolman** [comment]
We also used a jack up tower at the ONR New River Inlet projection around 2012.  Worked great.  It was a rental ($10K for one month with delivery).  106' vertical and we could take it down for lightning storms.  But if you are doing the north slope you need to deal with comms and power too. And control points.  (learning github!).

**Comment by KateBrodie** [comment]
@SRHarrison 

We got our jack-up tower from http://www.tashtowers.com/tower-trailers.php They have a range of towers. I think the 70ft tower cost on the order of 30K? But I'm not positive on that.

**Comment by SRHarrison** [comment]
Thanks @KateBrodie and @RobHolman . Those are some helpful details. I'll forward them along.

**Comment by mpalmsten** [comment]
Good question @SRHarrison. I added some of the info to the "towers" page on the wiki.
