### ISSUE TITLE
vBar wobbling and PIXInterpUV 

### ISSUE THREAD

**Issue by lbrisley** [Coastal-Imaging-Research-Network/Forum-Wiki#31]
Hello!
I am having an issue with the pixel sampling rate and cross shore resolution of my vBars that are positioned far from my camera, which is the area of interest. The cross shore resolution of my camera is 2.5m at a distance of 250m and increases to 5.5m at 400m which causes a wobble in the vBar when the pixel locations are sampled and then rounded down using the fix function in PIXRebuildCollect. Also, because of the low resolution at far distances, the vBar can span a width of 15-20m which seems to be creating an artificial signature in the pixel stacks when sampled at 10cm (hardcoded into the UAV toolbox). I adjusted the sampling rate to match the cross shore resolution at each location and I still see the wobble in the vBars, though not as pronounced.

I included the PIXInterpUV flag for vBars, as was recommended in PixCreateInstrument, to interpolate the XY location of the vBar pixels based on the 4 nearest pixels. That did not work because the resulting U and V matrices in the ‘r’ structure were larger than the XYZ matrix so the toolbox was not able to compute the XYZ locations. Somewhere in PIXRebuildCollect (approximately lines 190-213), four times the amount of pixels are sampled for each vBar but the step to average those four pixels to one location is missing. 

Has anyone had success with the PIXInterpUV flag or know how to handle the wobbling issue with vBars in an area with low cross shore resolution? I’ve included some pictures of the wobbling issue I described above. Matlab figures would have been better but alas that file type is not supported..

Thanks!
Lauren Brisley
NRL Student

![vBar400xylocs_1msampling](https://user-images.githubusercontent.com/51449917/61961222-b183d500-af8c-11e9-91bf-57a6372d8bbc.jpg)
![RectImagePIXInsts_1m](https://user-images.githubusercontent.com/51449917/61961230-b47ec580-af8c-11e9-9fde-a3b8b372732f.jpg)
![RectImagePIXInsts10cm](https://user-images.githubusercontent.com/51449917/61961237-b779b600-af8c-11e9-8084-0a87064ce9a0.jpg)
![VBarsVaryingSamplingRates](https://user-images.githubusercontent.com/51449917/61961240-b9dc1000-af8c-11e9-8530-768157e45fcb.jpg)

**Comment by chickadel** [comment]
Hi Lauren. Unfortunately, there isn't a great way to get around the problem of highly oblique imagery and the look-direction stretching of pixels (and the problems that introduces).  It means that you're probably restricted to using the vBar arrays closer to the origin, and in your images above that looks like where Y < 250m.  Away from this point the large pixel footprint smears the signature of the surface foam and makes it hard to track (both by eye and algorithmically). Moreover, the wobble you see in the timestacks is likely cause by the fact that the vertical displacement of the surface by waves passing by the pixels also results in a horizontal displacement in the view location, which in turn causes a velocity bias.  I corrected for this in the original paper (see Chickadel et al., 2003 JGR, section 2.8), but if the effect is big, then it's probably hard to overcome and will corrupt the signal so the technique doesn't work well.

As for the pixel interp flag, that might be broken, and wouldn't likely help your issue anyway.  However, maybe John Stanley has a new version?

**Comment by lbrisley** [comment]
It is unfortunate that most of the activity I am interested in occurs between 250m and 400m so with the current resolution I will be reevaluating my plan of analysis. Thank you @chickadel for your response!
