### ISSUE TITLE
SWH time series from single camera?

### ISSUE THREAD

**Issue by AndresSepulveda** [Coastal-Imaging-Research-Network/Forum-Wiki#35]
Hi,

I am recording from a pier with a single camera and I would like to obtain significant wave height time series from a  few points in the field of view. What software would you recommend for this?

Regards,

Andres

**Comment by SRHarrison** [comment]
Hi Andres,

Generally, it's difficult to obtain Hs from Argus style image products. One option is to get the distribution of run-up heights on the beach (e.g. Stockdon et al 2006, https://doi.org/10.1016/j.coastaleng.2005.12.005), but that includes swash zone processes and wave setup, etc. 

When in situ wave measurements are available, we have had very good results by training a deep-conv. neural network to estimate Hs from oblique imagery from fixed cameras (see Buscombe et al, 2019, https://doi.org/10.1016/j.coastaleng.2019.103593). It takes some effort to train the model, but then can be deployed and takes only milliseconds to estimate Hs for each photo. We're still working on optimizing the technique and identifying the sensitivities.

Best,
Shawn

**Comment by AndresSepulveda** [comment]
Thanks Shawn, we do have a way to measure the waves in situ for this camera.  I am downloading the code now to try this approach.
