### ISSUE TITLE
Separate matlab or python code to just extract Bright, Dark, Variance and Timex images from a video

### ISSUE THREAD

**Issue by sivaiahborra** [Coastal-Imaging-Research-Network/Forum-Wiki#38]
Dear All, 
As I am newbie to this forum and as well as beginner in Image processing techniques, Can anyone help in extracting Bright, Dark, Variance and timex images from a video of 10 minute duration as USGS. 
I have seen UAV Tool Box, somehow I understood that out of all matlab scripts and functions in that, buildRectProducts.m is somewhat related for my query but, I am not much clear that which script exactly I have to run to get only Bright, Dark, Variance and Timex images from a video and what are the other functions as well as sample data in UAV tool box to run that script. 

Please let me know if anyone already had involved in this kind of query or requirement. 
Thank you in Advance.

**Comment by SBFRF** [comment]
@anderdyl has some "unofficial" python stuff that he's been developing.

**Comment by sivaiahborra** [comment]
> 
> 
> @anderdyl has some "unofficial" python stuff that he's been developing.

Thank you for your response
