### ISSUE TITLE
Wiki development

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Forum-Wiki#4]
I started to add content to the wiki tonight. I'm modeling it on the original Argus Community Wiki (that no one ever used) and updating to reflect new directions. Check it out when you have time. @Coastal-Imaging-Research-Network/managers

**Comment by KateBrodie** [comment]
Looking good so far Meg!

Can we add pictures to the Wiki?

**Comment by mpalmsten** [comment]
Yes, but I haven't figured out how to do it.

**Comment by SRHarrison** [comment]
Nice... I like it. 
Question about the 'Sites' section: There are a number of cameras in New Zealand operating under the name of "[Cam-Era](https://www.niwa.co.nz/our-services/online-services/cam-era)". Essentially, they're Argus systems, except that they weren't made using the same work flow as the systems from CIL. Should these sites (and sites like these) be listed here alongside the traditional Argus sites? 
I'm happy to add the hardware details of some of these sites too if you want (some Cam-Era sites use different equipment depending on when they were installed and how near they are to mains power and internet).

**Comment by mpalmsten** [comment]
Yes, please add your sites and hardware details! 

I added my "Argus-like" cameras under the CIRN sites. I separated the long- and short-term installations. I want to keep them separate from the OSU/Deltares version because there are some differences (like the New Zealand cameras) in work flow and hardware. If you want to have a separate "Cam-Era" section, that works for me, or you can add them to the CIRN sites.

I am also going to add details about hardware and acquisition software, along with work flows for setting up the systems so that people can build their own systems following my example. Once I collect the data (I save all the video), I organize and process the long term data just like Rob and John do, using the CIL code. Each of my short-term installations have been for different purposes, so those data are processed in different ways.
