### ISSUE TITLE
Mirror of Argus Archive

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Forum-Wiki#5]
I'm working with another PI at NRL to establish an outward facing server that people can write to. This will be a great to mirror the OSU Argus data. 

I'm sure progress will be slow, but want to give everyone a heads up. 

I would tag Rob and John here, but I don't know if they are part of the group yet...

**Comment by SRHarrison** [comment]
keep us updated @mpalmsten, as we are interested in something similar.
