### ISSUE TITLE
Missing content on wiki

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Forum-Wiki#9]
Please review the wiki for missing content and provide content or useful suggestions on missing info.

**Comment by mpalmsten** [comment]
Re-organize wiki menu and navigation of wiki

**Comment by allisonpenko** [comment]
"Designing a Station" section of the Wiki needs to be added

**Comment by RobHolman** [comment]
yes ma’am.

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu
